#!/usr/bin/env bash


set -euo pipefail

GO_BUILD_IMAGE="${GO_BUILD_IMAGE:-golang:bullseye}"

echo "Building Matt's Conjur Tool"

# Use cd;pwd to ensure the path is absolute so can be
# used in a docker mount
repo_root="$(cd $(dirname ${BASH_SOURCE[0]})/..; pwd)"

if [[ "${1:-}" == "--docker" ]]; then
  if ! command -v docker; then
    echo "Docker not found, if you want to build without docker, install go locally and don't specify --docker"
  fi
  docker run\
    --rm \
    -e GOOS \
    -v ${repo_root}:/src \
    -w /src \
    "${GO_BUILD_IMAGE}" \
    go build -o output/mt cmd/policy_handler/main.go
else
  if ! command -v go; then
    echo "'go' not found, please install it or use ${0} --docker"
    exit 1
  fi
  pushd ${repo_root}
    go build -o output/mt cmd/policy_handler/main.go
  popd
fi

echo "Written Matts Tool binary written to ${repo_root}/output/mt"
